[package]
name = "wolges"
version = "0.1.0"
authors = ["Andy Kurnia"]
edition = "2018"
default-run = "auto"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 3

[dependencies]
csv = "1.1.6"
num_cpus = "1.13.0"
rand = "0.8.4"
rand_chacha = "0.3.1"
rustyline = "8.2.0"
rustyline-derive = "0.4.0"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
shell-words = "1.0.0"
tokio = { version = "1.8.1", features = ["full"] }

[[bin]]
name = "auto"
path = "src/main_auto.rs"

[[bin]]
name = "buildlex"
path = "src/main_build.rs"

[[bin]]
name = "endgame"
path = "src/main_endgame.rs"

[[bin]]
name = "json"
path = "src/main_json.rs"

[[bin]]
name = "leave"
path = "src/main_leave.rs"

[[bin]]
name = "lex"
path = "src/main_lex.rs"

[[bin]]
name = "shell"
path = "src/main_shell.rs"
